title: Dayda
name: National Aeronautics and Space administration 
user_description: Making NASA data more discoverable and usable.
notes_url: "https://simply-jekyll.netlify.app"
profile_pic: /assets/img/profile.png
favicon: /assets/img/favicon.png
copyright_name: Dayda
baseurl: "/"
url: http://national-aeronautics-and-space-administration.dayda.org
encoding: utf-8

theme: null
plugins:
  - jekyll-feed 
  - jekyll-sitemap 

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge

sass:
  style: compressed

disqus:
  shortname: raghuveerdotnet